@startuml
hide footbox

participant "main:Main" as m
participant "laby: Laby" as l
participant "pj:Perso" as p
actor "joueur" as j

activate j #00FF00

j -> m : "gauche"
activate m

m -> l : deplacerPerso(String action)
activate l
l -> l : getSuivant(int x, int y, String action)

l -> p : this.pj.x
activate p
l -> p : this.pj.y
deactivate p

l -> m : toString()

deactivate l
deactivate m
deactivate j

@enduml