@startuml
hide footbox

participant "main:Main" as main
participant "laby: LabyJeu" as l
participant "moteurJeu:MoteurJeu" as m
participant "dessin:DessinJeu" as r #FF8888
participant "labyDessin:LabyDessin" as d
participant "jeu:Jeu" as game #FF8888
participant "images:ChargerImage" as i #FF8888
participant "gc : Canvas" as gc #FF8888
create game
main-> game : new
create r
main-> r :new
main -> m : moteurJeu.launch(jeu,dessin)
activate m
create gc
m -> gc : new
m <-- gc
loop Timer
m -> d : dessinerJeu(jeu, gc)
activate d
group if (image == null)
create i
d -> i : new
deactivate i
else else
d -> d : null
end
d -> i  : getImageMonstre()
activate i
i -> d : image : Image
deactivate i
d -> gc : DrawImage(image,m*50,m*50,50,50)
activate gc
d <-- gc
deactivate gc
m <-- d
deactivate d
main <-- m
deactivate m
end

deactivate l

@enduml