@startuml
hide footbox

participant "main:Main" as main
participant "laby: LabyJeu" as l
participant "dessin:DessinJeu" as r #FF8888
participant "jeu:Jeu" as game #FF8888
participant "labyrinthe: Labyrinthe" as lab
participant "inventaire:Arraylist<ObjetRamassable>" as i
create game
main-> game : new
create r
main-> r :new

loop Timer


l -> game : update(duree,clavier)
activate l
activate game

l -> lab : attaquerMonstre()
activate lab
loop for(Monstre m : this.monstres)
group if (this.pj.monstreEnvironnent(m))
lab -> i : m.subirDegats(this.pj.getMeilleurDegats())
activate i #ffc320
lab <-- i
else else
lab -> lab : null

deactivate i
end group
end loop
game <-- lab
deactivate lab

game --> l
deactivate game
deactivate l

end

deactivate l

@enduml