@startuml
hide footbox

participant "main:Main" as main
participant "laby: LabyJeu" as l
participant "moteurJeu:MoteurJeu" as m
participant "dessin:DessinJeu" as r #FF8888
participant "labyDessin:LabyDessin" as d
participant "jeu:Jeu" as game #FF8888
participant "gc : Canvas" as gc #FF8888
create game
main-> game : new
create r
main-> r :new
main -> m : moteurJeu.launch(jeu,dessin)
activate m
create gc
m -> gc : new
m <-- gc
loop Timer
m -> d : dessinerJeu(jeu, gc)
activate d
loop for (Monstre m : labyJeu.getLaby().monstres)
d -> gc :fillOval(50*m.getX(),50*m.getY(),50,50)
activate gc
d <-- gc
deactivate gc
end group
m <-- d
deactivate d
main <-- m
deactivate m
end

deactivate l

@enduml