@startuml
title Inventaire et Perso

'''classe'''
class ObjetRamassable {

    + equipe : boolean;
    + ObjetRamassable(int x, int y)
    + toString() : String
}

class Potion{
    + Potion(int x, int y)
}

class Epee{
    + Epee(int x, int y)
}

class Position {
    int x;
    int y;

    + Position(int x, int y);
    + getX() ; int;
    + getY() : int;
    + equals(Position p) : boolean;
}

class Perso {

  + Perso(x : int, y : int)
  + etrePresent(dx : int, dy : int) : boolean
  + getX() : int
  + getY() : int
  + ramasser(objet : ObjetRamassable) : void
  + getInventaire() : ArrayList<ObjetRamassable>
}

'''relations'''
ObjetRamassable "*" --> "0..1" Perso: inventaire : ArrayList<ObjetRamassable>
ObjetRamassable  <|-- "Potion"
ObjetRamassable  <|-- "Epee"
Position <|--  Perso
Position <|--  ObjetRamassable



@enduml